### ISSUE TITLE
NPM?

### ISSUE THREAD

**Issue by OKNoah** [Evaw/objectDiff#1]
Can you put it on npm?

**Comment by OKNoah** [comment]
I've put it on npm

```bash
yarn add just-the-diff
npm install --save just-the-diff
```

https://www.npmjs.com/package/just-the-diff

**Comment by Evaw** [comment]
> I've put it on npm
> 
> yarn add just-the-diff
> npm install --save just-the-diff
> https://www.npmjs.com/package/just-the-diff

Thanks!
